---
# COPY this file to secrets.yml
development:
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  DATABASE_URL: sqlite://app/db/store/development.db
  DB_KEY: uIlZs0Q1+/KuRWRp1HdiLeqSx62WBTZ7aIzgfSnk9r0=
  SIGNING_KEY: nNuYJVHnMTPfArqFo3Rb81xvXoPDuqcdoUhjWVfGooE=
  VERIFY_KEY: j50XXfk5tXJ9oWomovLVOFlbgKKY/YSDPHAy4s1fA6U=
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTP
  GITHUB_ACCOUNT_URL: https://api.github.com/user
  GOOGLE_ACCOUNT_URL: https://www.googleapis.com/oauth2/v1/userinfo
  
test:
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  DATABASE_URL: sqlite://app/db/store/test.db
  DB_KEY: uIlZs0Q1+/KuRWRp1HdiLeqSx62WBTZ7aIzgfSnk9r0=
  SIGNING_KEY: nNuYJVHnMTPfArqFo3Rb81xvXoPDuqcdoUhjWVfGooE=
  VERIFY_KEY: j50XXfk5tXJ9oWomovLVOFlbgKKY/YSDPHAy4s1fA6U=
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTP
  GITHUB_ACCOUNT_URL: https://api.github.com/user
  GOOGLE_ACCOUNT_URL: https://www.googleapis.com/oauth2/v1/userinfo

production:
  MSG_KEY: <`rake newkey:msg`>
  DB_KEY: <`rake newkey:db`>
  DATABASE_URL: <do not edit - allow production server to set>
  SIGNING_KEY: <`rake newkey:signing`> # needed by client app; used in api tests
  VERIFY_KEY: <`rake newkey:signing`>
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTPS
  GITHUB_ACCOUNT_URL: https://api.github.com/user
  GOOGLE_ACCOUNT_URL: https://www.googleapis.com/oauth2/v1/userinfo